### ISSUE TITLE
Preview cutten and not rendering whole structure

### ISSUE THREAD

**Issue by Krutoy242** [BananaFructa/RatherEnoughImmersiveMultiblocks#2]
This `Solar Reflector` from `Immersive Technology` mod not rendered properly (one corner is cutted) and Mirrors are not rendered at all.

How its rendered: 
![image](https://github.com/user-attachments/assets/7cfff10e-52b7-4f49-bee3-2a2c386e930f)

How it should looks like: 
![image](https://github.com/user-attachments/assets/952ff066-d630-4c57-83f3-d22354a5f3cf)

Similar Issue with Steel Fluid Tank - its not rendered at all
![image](https://github.com/user-attachments/assets/cabf84c8-7618-47f8-b8c4-0f87c01b24d2)

**Comment by BananaFructa** [comment]
The Issue is cased by improper rendering on Immersive Technology's side. The rendering method simply calls the render functions provided through the IE multiblock interface. I may look into making a fix myself however that is highly unlikely in the near future.
